name: e2e

on:
  workflow_call:
  workflow_dispatch: # This makes the workflow manually triggerable
  schedule:
    - cron: "21 3 * * *" # Runs at 3:21 AM everyday

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
      - name: Build
        run: npm run build
      - name: Link
        run: npm link
      - name: Run e2e tests
        env:
          UNMOLD_API_TOKEN: ${{ secrets.UNMOLD_API_TOKEN }}
        run: npm run test:e2e
