name: main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # This makes the workflow manually triggerable

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Link
        run: npm link
      - name: Run integration tests
        env:
          UNMOLD_API_TOKEN: ${{ secrets.UNMOLD_API_TOKEN }}
        run: npm run test:integration
      - name: Run Docker build test
        run: npm run test:docker

  test-e2e:
    if: github.event_name != 'pull_request'
    needs: test
    uses: ./.github/workflows/e2e.yaml
    secrets: inherit

  publish-latest-image:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: test-e2e
    uses: ./.github/workflows/publish-docker-image.yaml
    secrets: inherit
